spring.application.name=Croma CRM Server

spring.config.import=optional:file:.env

spring.datasource.url=jdbc:postgresql://localhost:5432/croma_crm_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
