spring.application.name=Croma CRM Server

spring.datasource.url=jdbc:postgresql://localhost:5432/croma_crm_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
